---
default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: pretty-format-json
        args: [--autofix, '--no-sort-keys']
        exclude: .ipynb
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: .bumpversion.cfg
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [ --fix ]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
      - id: poetry-install
